CREATE DATABASE TroLyDB;
GO
USE TroLyDB;
GO
CREATE TABLE Tasks (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Title NVARCHAR(255) NOT NULL,
  Description NVARCHAR(MAX),
  Deadline DATETIME NULL,
  Priority INT NOT NULL DEFAULT 3,
  Status NVARCHAR(50) NOT NULL DEFAULT 'pending',
  CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
  LastNotified DATETIME
);

CREATE TABLE FilesLog (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  FileName NVARCHAR(255),
  FilePath NVARCHAR(500),
  AccessTime DATETIME,
  KeywordUsed NVARCHAR(255)
);
